import { h, money, photoUrl, cover } from './dom.js';
import { PRESETS, renderMannequin, validateBody } from './mannequin.js';

const CONDITIONS={like_new:'เหมือนใหม่',good:'สภาพดี',defect:'มีตำหนิ'};
const TAGS={front:'ด้านหน้า',back:'ด้านหลัง',label:'ป้าย',defect:'ตำหนิ'};
const MEASURES={shoulder:'ไหล่ (ความกว้าง)',chest:'รอบอก',waist:'รอบเอว',hip:'รอบสะโพก',length:'ความยาวชุด'};
const field=(label,node)=>h('label',{className:'field'},h('span',{},label),node);
const note=text=>h('p',{className:'muted seller-note'},text);
const input=(value,set,attrs={})=>h('input',{value:value??'',...attrs,onInput:e=>set(e.target.value)});
const select=(value,options,set)=>h('select',{onChange:e=>set(e.target.value)},Object.entries(options).map(([key,label])=>h('option',{value:key,selected:key===value},label)));
const uid=()=>crypto.randomUUID();

async function originalPhoto(file,tag='front') {
  if(!['image/jpeg','image/png','image/webp'].includes(file.type)) throw Error('รองรับเฉพาะ JPEG, PNG และ WebP');
  if(!file.size||file.size>10*1024*1024) throw Error('ไฟล์รูปต้องมีขนาดมากกว่า 0 และไม่เกิน 10 MB');
  const bitmap=await createImageBitmap(file); bitmap.close();
  const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await file.arrayBuffer())),n=>n.toString(16).padStart(2,'0')).join('');
  return {id:uid(),src:file,tag,hash};
}
async function transparentLayer(file) {
  if(file.type!=='image/png') throw Error('ชั้นชุดต้องเป็น PNG โปร่งใส');
  await originalPhoto(file);
  const bitmap=await createImageBitmap(file);
  if(bitmap.width*bitmap.height>25000000){bitmap.close();throw Error('PNG สำหรับลองชุดต้องไม่เกิน 25 ล้านพิกเซล');}
  const canvas=document.createElement('canvas');canvas.width=bitmap.width;canvas.height=bitmap.height;
  const context=canvas.getContext('2d');context.drawImage(bitmap,0,0);bitmap.close();
  const pixels=context.getImageData(0,0,canvas.width,canvas.height).data;
  let clear=false,visible=false;for(let i=3;i<pixels.length;i+=4){clear||=pixels[i]===0;visible||=pixels[i]>0;if(clear&&visible)break;}
  if(!clear||!visible)throw Error('PNG ต้องมีทั้งรูปชุดและพื้นที่โปร่งใส ไม่มีระบบตัดพื้นหลังอัตโนมัติ');
  return {id:uid(),slot:'base',src:file,x:0,y:0,scale:1};
}

export function openCosplayListing(ctx,id=null){
  const owner=ctx.state.settings.currentUserId;
  if(!owner){ctx.toast('กรุณาเลือกบัญชีก่อนลงชุดให้เช่า');return;}
  const existing=id&&ctx.state.listings.find(l=>l.id===id);
  if(id&&(!existing||existing.sellerId!==owner||existing.status==='deleted')){ctx.toast('ไม่สามารถแก้ไขรายการนี้ได้');return;}
  const draft=existing?structuredClone(existing):{character:'',title:'',series:'',description:'',components:[],condition:'good',photos:[],coverId:null,defects:[],costumeLayers:[],lengthTarget:'knee',sizeVariants:[],status:'active'};
  let components=draft.components.join(', '),step=0,errors=[],busy=false,selectedSize=0;
  const body={...(PRESETS.Regular||{height:165,chest:90,waist:72,hip:96,shoulder:40}),preset:'Regular'};
  const refresh=()=>ctx.modal(existing?'แก้ไขชุดให้เช่า':'ลงชุดให้เช่า',render,{wide:true});
  const guard=()=>{if(ctx.state.settings.currentUserId!==owner)throw Error('บัญชีเปลี่ยนแล้ว กรุณาปิดแบบฟอร์มและเปิดใหม่ด้วยบัญชีเจ้าของร่าง');};
  const act=fn=>()=>ctx.task(async()=>{try{guard();errors=[];await fn();}catch(err){errors=[err.message||'ไม่สามารถทำรายการได้'];busy=false;refresh();}});
  const button=(label,fn,secondary=false,attrs={})=>h('button',{type:'button',className:`btn${secondary?' secondary':''}`,disabled:busy,...attrs,onClick:act(fn)},label);
  const validate=stage=>{
    const e=[];
    if(stage===0){if(!draft.character.trim())e.push('ระบุชื่อตัวละคร');if(!draft.title.trim())e.push('ระบุชื่อประกาศ');if(!draft.series.trim())e.push('ระบุชื่อเรื่อง / เกม');if(!draft.components.length)e.push('ระบุส่วนประกอบที่ได้รับ');if(!draft.description.trim())e.push('เพิ่มคำอธิบาย');}
    if(stage===1){if(!draft.sizeVariants.length)e.push('เลือกอย่างน้อย 1 ไซซ์');for(const v of draft.sizeVariants)for(const [key,label]of Object.entries(MEASURES))if(!Number.isFinite(Number(v.measurements[key]))||Number(v.measurements[key])<10||Number(v.measurements[key])>250)e.push(`${v.size}: ${label} ต้องอยู่ระหว่าง 10–250 ซม.`);}
    if(stage===2){if(!draft.photos.some(p=>p.tag==='front'))e.push('เพิ่มรูปต้นฉบับด้านหน้าอย่างน้อย 1 รูป');if(draft.condition==='defect'&&!draft.defects.length)e.push('เพิ่มรายละเอียดตำหนิ');for(const d of draft.defects)if(!draft.photos.some(p=>p.id===d.photoId&&p.tag==='defect')||!d.type||!d.severity||!d.description.trim())e.push('ระบุรูปตำหนิ ประเภท ระดับ และคำอธิบายให้ครบ');}
    if(stage===3)for(const v of draft.sizeVariants)if(!Number.isFinite(Number(v.price))||Number(v.price)<=0||Number(v.price)>1000000)e.push(`${v.size}: ระบุราคา 1–1,000,000 บาท`);
    return e;
  };
  const details=()=>h('section',{className:'stack'},h('h3',{},'01 / เรื่องราวของชุด'),h('div',{className:'panel-form-grid'},field('ตัวละคร *',input(draft.character,v=>draft.character=v,{maxLength:100})),field('ชื่อประกาศ *',input(draft.title,v=>draft.title=v,{maxLength:160})),field('เรื่อง / เกม *',input(draft.series,v=>draft.series=v,{maxLength:120})),field('สภาพชุด',select(draft.condition,CONDITIONS,v=>{draft.condition=v;refresh();}))),field('ส่วนประกอบที่ได้รับ *',input(components,v=>{components=v;draft.components=v.split(',').map(s=>s.trim()).filter(Boolean);},{placeholder:'เสื้อ, กระโปรง, โบว์',maxLength:600})),field('คำอธิบาย *',h('textarea',{rows:4,value:draft.description,maxLength:3000,onInput:e=>draft.description=e.target.value})),button('ช่วยร่างคำอธิบาย',()=>{draft.description=[draft.title.trim(),draft.character&&`ชุดตัวละคร ${draft.character}`,draft.series&&`จาก ${draft.series}`,draft.components.length&&`ประกอบด้วย ${draft.components.join(', ')}`,`สภาพ: ${CONDITIONS[draft.condition]}`].filter(Boolean).join('\n');refresh();},true),note('เครื่องมือร่างข้อความสาธิต ใช้เฉพาะข้อมูลที่คุณกรอก โปรดตรวจทานก่อนเผยแพร่'));
  const variants=()=>h('section',{className:'stack'},h('h3',{},'02 / ไซซ์และขนาดจริง'),note('แต่ละไซซ์มี 1 ชิ้นสำหรับให้เช่า วัดรอบตัวเป็นเซนติเมตร ยกเว้นไหล่เป็นความกว้าง'),h('div',{className:'seller-sizes'},...['S','M','L','XL'].map(size=>{const v=draft.sizeVariants.find(v=>v.size===size);return button(`${v?'✓ ': '+ '}${size}${v?.stock===0?' · ปิดรับเช่า':''}`,()=>{if(v){if(v.stock===0)return;draft.sizeVariants=draft.sizeVariants.filter(q=>q!==v);}else draft.sizeVariants.push({id:uid(),size,stock:1,price:'',measurements:{shoulder:'',chest:'',waist:'',hip:'',length:''}});refresh();},!v,{disabled:busy||v?.stock===0,'aria-pressed':!!v});})),...draft.sizeVariants.map(v=>h('div',{className:'seller-card stack'},h('strong',{},`ไซซ์ ${v.size} · ${v.stock===0?'ปิดรับเช่า — เก็บประวัติเดิม':'พร้อมให้เช่า 1 ชิ้น'}`),h('div',{className:'seller-measures'},...Object.entries(MEASURES).map(([key,label])=>field(`${label} (ซม.)`,input(v.measurements[key],n=>v.measurements[key]=n===''?'':Number(n),{type:'number',min:10,max:250,step:0.1,disabled:v.stock===0})))))),field('ชุดควรยาวถึง',select(draft.lengthTarget,{waist:'เอว',knee:'เข่า',ankle:'ข้อเท้า'},v=>draft.lengthTarget=v)));
  const addPhotos=files=>act(async()=>{busy=true;refresh();try{const added=[];for(const file of files){const p=await originalPhoto(file);if([...draft.photos,...added].some(q=>q.hash===p.hash))throw Error('รูปนี้ซ้ำกับรูปที่เพิ่มแล้ว');added.push(p);}guard();draft.photos.push(...added);draft.coverId||=draft.photos[0]?.id;}finally{busy=false;}refresh();})();
  const preview=()=>h('div',{className:'seller-preview'},h('div',{className:'seller-mannequin'},validateBody(body).length?note('ไม่สามารถแสดงหุ่นมาตรฐาน'):renderMannequin(body,draft,draft.sizeVariants[selectedSize]||draft.sizeVariants[0],{guides:true})),h('div',{className:'stack'},cover(draft)?h('img',{className:'seller-original',src:photoUrl(cover(draft)),alt:'ภาพชุดต้นฉบับ'}):note('เพิ่มรูปด้านหน้าเพื่อดูภาพต้นฉบับ'),note(draft.costumeLayers.length?'ภาพซ้อนบนหุ่น Regular มาตรฐานเพื่อจัดตำแหน่ง ไม่ใช่การรับประกันความพอดี':'ยังไม่มี PNG โปร่งใส จึงแสดงภาพต้นฉบับคู่หุ่นมาตรฐาน ยังไม่สามารถแสดงชุดนี้บนหุ่นได้')));
  const photos=()=>h('section',{className:'stack'},h('h3',{},'03 / รูปต้นฉบับและพรีวิว'),note('เก็บไฟล์ต้นฉบับในเบราว์เซอร์นี้ ไม่มีการส่งภาพไปบริการภายนอก'),field('เพิ่มภาพ JPEG / PNG / WebP · ไม่เกิน 10 MB ต่อรูป',h('input',{type:'file',accept:'image/jpeg,image/png,image/webp',multiple:true,disabled:busy,onChange:e=>addPhotos([...e.target.files])})),h('div',{className:'panel-photo-grid'},...draft.photos.map((p,i)=>h('article',{className:'panel-photo-card'},h('img',{src:photoUrl(p),alt:`รูปต้นฉบับ ${i+1}`}),field(`มุมภาพ ${i+1}`,select(p.tag,TAGS,v=>{p.tag=v;refresh();})),button(draft.coverId===p.id?'✓ ภาพปก':'ใช้เป็นปก',()=>{draft.coverId=p.id;refresh();},true),button('ลบภาพ',()=>{draft.photos=draft.photos.filter(q=>q.id!==p.id);draft.defects=draft.defects.filter(d=>d.photoId!==p.id);if(draft.coverId===p.id)draft.coverId=draft.photos[0]?.id||null;refresh();},true)))),draft.condition==='defect'&&h('div',{className:'stack'},h('h4',{},'แจ้งตำหนิอย่างตรงไปตรงมา'),...draft.defects.map((d,i)=>h('div',{className:'seller-card stack'},field('ภาพตำหนิ',select(d.photoId,{'':'เลือกรูป',...Object.fromEntries(draft.photos.filter(p=>p.tag==='defect').map((p,j)=>[p.id,`ตำหนิ ${j+1}`]))},v=>d.photoId=v)),h('div',{className:'panel-form-grid'},field('ประเภท',select(d.type,{stain:'คราบ',snag:'ด้ายรัน',fade:'สีซีด',tear:'ขาด',other:'อื่น ๆ'},v=>d.type=v)),field('ระดับ',select(d.severity,{minor:'เล็กน้อย',visible:'มองเห็นชัด',functional:'กระทบการใช้งาน'},v=>d.severity=v))),field('อธิบายตำแหน่งและลักษณะ',input(d.description,v=>d.description=v,{maxLength:500})),button('ลบตำหนิ',()=>{draft.defects.splice(i,1);refresh();},true))),button('เพิ่มรายละเอียดตำหนิ',()=>{draft.defects.push({photoId:'',type:'stain',severity:'minor',description:''});refresh();},true)),h('div',{className:'seller-card stack'},h('h4',{},'พรีวิวบนหุ่นมาตรฐาน'),field('ไซซ์ที่ใช้พรีวิว',select(String(selectedSize),Object.fromEntries(draft.sizeVariants.map((v,i)=>[String(i),v.size])),v=>{selectedSize=Number(v);refresh();})),preview(),field('เพิ่ม PNG โปร่งใสสำหรับซ้อนชุด',h('input',{type:'file',accept:'image/png',disabled:busy,onChange:e=>{const file=e.target.files[0];if(file)act(async()=>{busy=true;refresh();try{const layer=await transparentLayer(file);guard();draft.costumeLayers.push(layer);}finally{busy=false;}refresh();})();}})),note('ไม่มีระบบตัดพื้นหลังอัตโนมัติ ปรับตำแหน่งบนพื้นที่ 400 × 600'),...draft.costumeLayers.map((layer,i)=>h('div',{className:'seller-layer'},field(`ชั้น ${i+1}`,select(layer.slot,{wig:'วิก',base:'ชุดหลัก',outer:'เสื้อคลุม',shoes:'รองเท้า',accessory:'เครื่องประดับ'},v=>{layer.slot=v;refresh();})),...['x','y','scale'].map(key=>field(key==='scale'?'ขนาด':`ตำแหน่ง ${key}`,input(layer[key],v=>layer[key]=Number(v),{type:'number',min:key==='scale'?0.1:key==='x'?-400:-600,max:key==='scale'?3:key==='x'?400:600,step:key==='scale'?0.05:1,onChange:()=>refresh()}))),button('ลบชั้น',()=>{draft.costumeLayers.splice(i,1);refresh();},true)))));
  const recommendation=v=>{
    const prices=ctx.state.listings.filter(l=>l.id!==draft.id&&l.status==='active'&&l.condition===draft.condition).flatMap(l=>l.sizeVariants.filter(q=>q.size===v.size&&q.stock>0&&Number.isFinite(q.price)&&q.price>0).map(q=>q.price)).sort((a,b)=>a-b);
    const count=prices.length,median=count%2?prices[Math.floor(count/2)]:(prices[count/2-1]+prices[count/2])/2;
    return h('div',{},note(`เปรียบเทียบสภาพ ${CONDITIONS[draft.condition]} / ไซซ์ ${v.size}: ${count} รายการ · ราคาเช่าต่อวันในข้อมูลเบราว์เซอร์นี้ (รวมรายการสาธิต)`),count>=3?button(`ใช้ค่ากลาง ${money(median)} / วัน`,()=>{v.price=Math.round(median);refresh();},true,{disabled:busy||v.stock===0}):note('ข้อมูลไม่เพียงพอ: ต้องมีอย่างน้อย 3 รายการ จึงแสดงราคาแนะนำ'));
  };
  const review=()=>h('section',{className:'stack'},h('h3',{},'04 / ราคาเช่าและตรวจประกาศ'),...draft.sizeVariants.map(v=>h('div',{className:'seller-card stack'},field(`ราคาเช่าต่อวัน ไซซ์ ${v.size} (บาท)`,input(v.price,n=>v.price=n===''?'':Number(n),{type:'number',min:1,max:1000000,step:1,disabled:v.stock===0})),recommendation(v))),h('div',{className:'seller-card stack'},h('h3',{},draft.title),note(`${draft.character}${draft.series?' · '+draft.series:''} · ${CONDITIONS[draft.condition]}`),h('p',{className:'seller-description'},draft.description),h('p',{},`ได้รับ: ${draft.components.join(', ')}`),h('p',{},`${draft.photos.length} ภาพต้นฉบับ · ${draft.defects.length} ตำหนิที่แจ้ง`),preview()),note('เผยแพร่ในตลาดสาธิตของเบราว์เซอร์นี้ แต่ละไซซ์พร้อมให้เช่า 1 ชิ้น ไม่มีการรับเงินจริง'));
  async function next(){errors=validate(step);if(errors.length){refresh();return;}if(step<3){step++;refresh();return;}errors=[0,1,2,3].flatMap(validate);if(errors.length){refresh();return;}guard();busy=true;refresh();try{await ctx.run('listing.save',{listing:draft});ctx.toast(existing?'บันทึกชุดให้เช่าแล้ว':'เผยแพร่ชุดให้เช่าแล้ว');ctx.close();ctx.openCloset('selling');}finally{busy=false;}}
  const render=()=>h('form',{className:'cosplay-seller stack',onSubmit:e=>{e.preventDefault();if(!busy)act(next)();}},h('ol',{className:'seller-steps'},...['ข้อมูลชุด','ไซซ์ / ขนาด','รูป / พรีวิว','ราคาเช่า / เผยแพร่'].map((label,i)=>h('li',{className:i===step?'current':'','aria-current':i===step?'step':undefined},h('span',{},`0${i+1}`),label))),errors.length>0&&h('div',{className:'panel-error',role:'alert'},...errors.map(e=>h('p',{},e))),ctx.state.settings.currentUserId!==owner&&h('p',{className:'panel-error',role:'alert'},'บัญชีเปลี่ยนแล้ว กรุณาเปิดแบบฟอร์มใหม่'),[details,variants,photos,review][step](),h('div',{className:'panel-footer'},step>0?button('ย้อนกลับ',()=>{step--;errors=[];refresh();},true):note('ร่างจะเก็บไว้ระหว่างขั้นตอนจนกว่าจะปิด'),h('button',{className:'btn',type:'submit',disabled:busy||ctx.state.settings.currentUserId!==owner},busy?'กำลังตรวจสอบ…':step===3?(existing?'บันทึกการแก้ไข':'เผยแพร่ชุดให้เช่า'):'ถัดไป')));
  refresh();
}


