import {h,money,photoUrl,cover} from './dom.js';
import {lenderNextAction,lenderSummary,listingRentalSchedule} from './lender-presenter.js';

// Direct Figma exports; intrinsic SVG dimensions are retained.
const asset=(page,name)=>h('img',{class:'partner-asset',src:`assets/lender-figma/${page}-${name}.svg`,alt:''});
const mark=()=>h('span',{class:'partner-mark','aria-hidden':'true'},h('b',{},'TOO'),h('span',{},'SUEA'),h('span',{},'PHA'));
const conditions={like_new:'เหมือนใหม่',good:'สภาพดี',defect:'มีตำหนิ'};
const shortDate=value=>new Date(`${value}T12:00:00`).toLocaleDateString('th-TH',{day:'numeric',month:'short'});
const tableHead=labels=>h('thead',{},h('tr',{},...labels.map(x=>h('th',{scope:'col'},x))));
const cell=(primary,secondary)=>h('td',{},h('b',{},primary),secondary&&h('small',{},secondary));
const items=b=>b.items||[{listingId:b.listingId,size:b.size,listingSnapshot:b.listingSnapshot}];
const RETURN_STATUSES=new Set(['renting','return_preparing','return_shipped','return_received','inspection','cleaning','completed']);

export function createLenderPortal(ctx,tab){
  const {state,actorId,accounts,editListing,manageListing,manageBooking,showLedger,showNotices,statusLabels}=ctx;
  const active=['overview','listings','requests','returns'].includes(tab)?tab:'listings';
  const page={overview:0,listings:1,requests:2,returns:3}[active];
  const profile=state.profiles.find(x=>x.id===actorId);
  const own=state.listings.filter(x=>x.sellerId===actorId&&x.status!=='deleted');
  const bookings=state.rentals.filter(x=>x.sellerId===actorId);
  const summary=lenderSummary(state,actorId);
  const action=(label,fn,className='partner-primary',extra={})=>h('button',{type:'button',class:className,onclick:fn,...extra},label);
  const add=(full=false)=>action([asset(page,page<2?'imgSvg5':'imgSvg11'),full?'ลงชุดให้เช่า (Add my closet)':'ลงชุดให้เช่า'],()=>editListing());
  const title=(text,copy,badge=false)=>h('div',{class:'partner-page-head'},h('div',{},h('div',{class:'partner-title-row'},h('h1',{},text),badge?h('span',{class:'partner-status'},'Status'):null),h('p',{},copy)),add());
  const header=h('header',{class:'partner-header'},
    h('a',{class:'partner-brand',href:'#home','aria-label':'TooSueaPha หน้าแรก'},mark(),h('span',{class:'partner-lockup'},h('span',{},h('strong',{},'Too'),h('span',{},'SueaPha'),h('i',{},'/'),h('b',{},'PARTNER')),h('small',{},'TooSueaPha Rental System'))),
    h('nav',{class:'partner-mode','aria-label':'เลือกโหมด'},h('a',{href:'#shop'},'เช่า'),h('a',{href:'#closet/overview',class:'active'},'ปล่อยเช่า')),
    h('form',{class:'partner-search',role:'search',onsubmit:e=>{e.preventDefault();ctx.search(e.currentTarget.querySelector('input').value)}},asset(page,page<2?'imgSvg':'imgSvg4'),h('input',{type:'search','aria-label':'ค้นหา Marketplace',placeholder:"ลองค้นหาด้วย ชื่อชุด, รหัส SKU, ชื่อนางแบบ หรือชื่อตัวละคร (เช่น 'ชุด Genshin Raiden', 'วิกผม Hu Tao')"})),
    h('div',{class:'partner-actions'},action(asset(page,page<2?'imgSvg1':'imgSvg5'),showNotices,'partner-icon',{'aria-label':'การแจ้งเตือน'}),action([h('span',{class:'partner-avatar'},h('span',{},profile.name.slice(0,2).toUpperCase())),h('span',{class:'partner-profile-name'},h('b',{},`@${profile.name}`),h('small',{},`${profile.name} (Atelier)`)),asset(page,page<2?'imgVector':'imgVector1')],accounts,'partner-profile',{'aria-label':'สลับบัญชี'})));
  const nav=(key,label,icon,count)=>h('a',{href:`#closet/${key}`,class:active===key||(key==='requests'&&active==='returns')?'active':'','aria-current':active===key||(key==='requests'&&active==='returns')?'page':null},asset(page,icon),h('span',{},label),count!=null?h('b',{},count):null);
  const sidebar=h('aside',{class:'partner-sidebar'},h('p',{},'เมนูหลักผู้ปล่อยเช่า'),h('nav',{'aria-label':'เมนูผู้ปล่อยเช่า'},nav('overview','ภาพรวม (Overview)',page<2?'imgSvg2':'imgSvg6'),nav('listings',active==='returns'?'คลังชุด (My Listings)':'ตู้เสื้อผ้า (My Closet)',page<2?'imgSvg3':'imgSvg7',own.length),nav('requests','การเช่า',page<2?'imgSvg4':'imgSvg8')));
  function productCell(item,copy){return h('td',{},h('div',{class:'partner-product-cell'},h('img',{class:'partner-product-image',src:photoUrl(item.image||cover(item)),alt:''}),h('span',{},h('b',{},item.title||'ชุดเช่า'),h('small',{},copy))))}
  function empty(copy){return h('div',{class:'partner-empty'},h('div',{class:'partner-empty-art','aria-hidden':'true'},h('div',{class:'empty-disc'}),h('div',{class:'empty-sheet'},...Array.from({length:4},()=>h('i'))),h('div',{class:'empty-mini'},h('i'),h('i')),h('div',{class:'empty-dots'},h('i'),h('i'),h('i')),h('i',{class:'empty-diamond'})),h('p',{},copy))}
  function overview(){
    const popular=[...own].sort((a,b)=>listingRentalSchedule(state,actorId,b.id).length-listingRentalSchedule(state,actorId,a.id).length).slice(0,3);
    return h('div',{class:'partner-view overview-view'},h('div',{class:'partner-overview-grid'},
      h('div',{class:'partner-overview-left'},h('article',{class:'consignment-card'},h('div',{class:'consignment-copy'},h('span',{class:'partner-kicker'},'CONSIGNMENT CARE'),h('h1',{},'ส่งชุดเข้าคลังกลาง',h('br'),'(Consignment Care)'),h('p',{},'ฝากส่งชุดให้เราดูแลครบวงจร ตรวจเช็ก จัดเก็บ',h('br'),'ซักอบ สแกน 3D และแพ็กจัดส่งผู้เช่าอัตโนมัติ'),h('div',{class:'consignment-cta'},action(['ส่งชุดเข้าคลัง',asset(0,'imgVector1')],()=>ctx.consignment(),'partner-light'),h('small',{},'ฟรีค่าตรวจสภาพและจัดเก็บ'))),h('div',{class:'consignment-steps'},h('div',{},h('span',{},'ขั้นตอนส่งชุด'),h('small',{},'สะดวก รวดเร็ว')),h('ol',{},...['กรอกข้อมูล & นัดขนส่งรับชุด','สแกน 3D ตรวจเช็ก & ซักอบ','ปล่อยเช่าทันที รับรายได้ Escrow'].map((x,i)=>h('li',{},h('b',{},i+1),x))))),
        h('section',{class:'popular-list'},h('div',{class:'partner-section-title'},h('h2',{},'ชุดยอดนิยมที่มีความต้องการเช่าสูง'),h('a',{href:'#closet/listings'},'ดูชุดยอดฮิตทั้งหมด →')),h('div',{class:'popular-rows'},...(popular.length?popular.map(item=>h('article',{},h('img',{src:photoUrl(cover(item)),alt:''}),h('div',{},h('b',{},item.title),h('small',{},`${item.character} · ${item.sizeVariants.map(v=>v.size).join(' / ')}`)),h('div',{class:'popular-price'},h('b',{},money(Math.min(...item.sizeVariants.map(v=>v.price))),h('span',{},' / วัน')),h('small',{},`${listingRentalSchedule(state,actorId,item.id).length} การจอง`)))):[empty('ยังไม่มีชุดในคลัง')])))),
      h('aside',{class:'partner-overview-right'},h('article',{class:'seller-center-card'},h('div',{class:'seller-center-brand'},mark(),h('div',{},h('span',{},'TooSueaPha'),h('b',{},'Seller Center'))),h('p',{},'เพิ่มรายการชุดในไม่กี่นาที ติดตามและจัดการคำสั่งเช่าทั้งหมดในที่เดียว เริ่มต้นปล่อยเช่าชุดวันนี้!'),add(true)),
        h('article',{class:'partner-tier-card'},h('div',{class:'tier-label'},h('span',{class:'tier-icon'},asset(0,'imgSvgDiamondBadgeIcon')),h('div',{},h('small',{},'ระดับพาร์ทเนอร์'),h('b',{},'Tier 1: Master Cosplay Atelier'))),h('div',{class:'tier-account'},h('div',{},h('small',{},'สถานะบัญชี'),h('span',{class:'tier-health',title:'สถานะตัวอย่างตามแบบ Figma'},asset(0,'imgSvg6'),'ยอดเยี่ยม')),h('div',{},h('small',{},'เครดิต & วงเงิน Escrow'),action(money(summary.earnings.available+summary.earnings.pending),showLedger,'tier-balance',{'aria-label':'ดูรายได้และ Escrow จำลอง'}))),h('div',{class:'tier-fees'},h('div',{},h('small',{},'ประเภทสินค้าเช่า'),h('small',{},'ค่าบริการให้เช่า')),h('div',{},h('span',{},'ค่าบริการจัดวางให้เช่าชุด'),h('b',{},'7.0%')),h('div',{},h('span',{},'ค่าบริการชำระเงิน & ระบบ Escrow'),h('b',{},'3.0%')),h('div',{class:'tier-shield'},h('span',{},asset(0,'imgSvg7'),'ประกันภัยชุดชำรุด (Damage Shield)'),h('b',{},'ฟรี (0%)'))),action('ดูรายละเอียดเงื่อนไขการหักค่าธรรมเนียมและสิทธิพิเศษ Tier',()=>ctx.feeInfo(),'tier-terms')))));
  }
  function listings(){
    let current=1,limit=25;const tbody=h('tbody'),footer=h('footer',{class:'partner-pagination'});
    function draw(){const count=Math.max(1,Math.ceil(own.length/limit));current=Math.min(current,count);tbody.replaceChildren(...own.slice((current-1)*limit,current*limit).map(item=>h('tr',{},productCell(item,`SKU: ${item.id.toUpperCase()} • ${(item.components||[]).join(' + ')||item.character}`),cell(`ไซซ์ ${item.sizeVariants.map(v=>v.size).join(' / ')}`,conditions[item.condition]),cell(money(Math.min(...item.sizeVariants.map(v=>v.price)))) ,cell('—'),h('td',{},h('span',{class:`partner-pill ${item.status}`},({active:'พร้อมให้เช่า',paused:'พักให้เช่า',reserved:'ถูกจอง',sold:'ไม่พร้อมให้เช่า'}[item.status]||item.status))),h('td',{},action('จัดการ',()=>manageListing(item),'partner-row-action')))));
      if(!own.length)tbody.append(h('tr',{},h('td',{colspan:6},empty('คุณยังไม่มีชุดให้เช่า'))));
      footer.replaceChildren(h('div',{},'รายการต่อหน้า:',h('select',{'aria-label':'รายการต่อหน้า',onchange:e=>{limit=Number(e.target.value);current=1;draw()}},...[10,25,50].map(n=>h('option',{value:n,selected:n===limit},n))),h('span',{},'|'),h('span',{},`แสดง ${own.length?(current-1)*limit+1:0} - ${Math.min(current*limit,own.length)} จากทั้งหมด ${own.length} รายการ`)),h('div',{},action(asset(1,'imgSvg6'),()=>{current--;draw()},'partner-page-number',{disabled:current===1,'aria-label':'หน้าก่อนหน้า'}),...Array.from({length:count},(_,i)=>action(String(i+1),()=>{current=i+1;draw()},`partner-page-number ${current===i+1?'active':''}`,{'aria-current':current===i+1?'page':null})),action(asset(1,'imgSvg7'),()=>{current++;draw()},'partner-page-number',{disabled:current===count,'aria-label':'หน้าถัดไป'})));
    }draw();
    return h('div',{class:'partner-view closet-table-view'},title('ตู้เสื้อผ้า (My Closet)','รายการสั่งเช่าของคุณ',true),h('div',{class:'partner-table-card'},h('div',{class:'partner-table-scroll'},h('table',{class:'partner-table'},tableHead(['สินค้า / รหัส SKU','ไซซ์ & สภาพ','ราคาเช่า','ค่าส่ง/รับสินค้า','สถานะ','การจัดการ']),tbody)),footer));
  }
  function orders(returns){
    let selected=returns?'renting':'waiting',query='',sort='latest',max=Infinity,category='',brand='',size='',sku='';
    const groups=returns?[['renting','กำลังเช่า',['renting']],['due','ถึงกำหนดคืน',['return_preparing']],['returning','กำลังรับคืน',['return_shipped']],['inspect','ตรวจสภาพ/ทำความสะอาด',['inspection','cleaning']],['received','ร้านได้รับคืน',['return_received']],['complete','พร้อมให้เช่า',['completed']]]:[['all','คำสั่งเช่า',null],['waiting','รอการจัดส่ง',['paid','preparing','pending','confirmed']],['progress','กำลังดำเนินการ',['outbound_shipped','outbound_transit','renting','return_preparing','return_shipped','return_received','inspection','cleaning']],['complete','สำเร็จ',['completed']],['cancel','ยกเลิก',['cancelled']]];
    const source=returns?bookings.filter(b=>RETURN_STATUSES.has(b.status)):bookings;
    const host=h('div'),tabs=h('div',{class:'partner-status-tabs'});
    function draw(){const statuses=groups.find(g=>g[0]===selected)?.[2];let rows=source.filter(b=>!statuses||statuses.includes(b.status)).filter(b=>b.totalPrice<=max).filter(b=>{const parts=items(b),products=parts.map(p=>state.listings.find(l=>l.id===p.listingId));return (!category||products.some(l=>l?.occasionCategory===category))&&(!brand||products.some(l=>l?.brand===brand))&&(!size||parts.some(p=>p.size===size))&&(!sku||parts.some(p=>p.listingId===sku))&&`${b.id} ${state.profiles.find(p=>p.id===b.renterId)?.name} ${parts.map(p=>`${p.listingId} ${p.listingSnapshot?.title||''}`).join(' ')}`.toLowerCase().includes(query.toLowerCase())});rows.sort((a,b)=>sort==='oldest'?a.createdAt-b.createdAt:sort==='price'?a.totalPrice-b.totalPrice:b.createdAt-a.createdAt);
      tabs.replaceChildren(...groups.map(([key,label],i)=>action([i===0?asset(page,'imgSvg'):null,label],()=>{selected=key;draw()},selected===key?'active':'',{'aria-pressed':String(selected===key)})));
      host.replaceChildren(rows.length?h('div',{class:'partner-table-card'},h('div',{class:'partner-table-scroll'},h('table',{class:'partner-table booking-table'},tableHead(['สินค้า / รหัส SKU','วันเช่า','ค่าส่ง/รับสินค้า','สถานะ','การจัดการ']),h('tbody',{},...rows.map(b=>{const parts=items(b),first=parts[0],next=lenderNextAction(b,actorId);return h('tr',{},productCell({...first.listingSnapshot,title:parts.map(p=>p.listingSnapshot?.title||'ชุดเช่า').join(' + ')},`SKU: ${first.listingId.toUpperCase()} • ไซซ์ ${parts.map(p=>p.size).join(' / ')}`),cell(`${shortDate(b.pickupDate)}–${shortDate(b.returnDate)}`),cell('—'),h('td',{},h('span',{class:`partner-pill ${b.status}`},b.status==='preparing'?'เตรียมจัดส่ง':statusLabels[b.status]||b.status)),h('td',{},action('จัดการ',()=>manageBooking(b),'partner-row-action',{'aria-label':`จัดการ Booking ${b.id} · ${next?.label||'ดูรายละเอียด'}`})))}))))):empty(returns?'คุณยังไม่มีรายการรับชุดคืน':'คุณยังไม่มีคำสั่งเช่าในสถานะนี้'));
    }
    const select=(label,options,update,className='')=>h('label',{class:`partner-select ${className}`},h('select',{'aria-label':label,onchange:e=>{update(e.target.value);draw()}},h('option',{value:''},label),...options.map(([v,t])=>h('option',{value:v},t))),asset(page,'imgVector'));
    const filterControls=h('div',{class:'partner-filter-options'},h('div',{},select('หมวดหมู่สินค้า',[...new Set(own.map(x=>x.occasionCategory).filter(Boolean))].map(x=>[x,x]),v=>category=v),select('แบรนด์',[...new Set(own.map(x=>x.brand).filter(Boolean))].map(x=>[x,x]),v=>brand=v),select('ไซซ์',[...new Set(own.flatMap(x=>x.sizeVariants.map(v=>v.size)))].map(x=>[x,x]),v=>size=v),select('SKU',own.map(x=>[x.id,x.id]),v=>sku=v)),h('div',{},select('ราคาทั้งหมด',[['1000','ไม่เกิน ฿1,000'],['3000','ไม่เกิน ฿3,000'],['5000','ไม่เกิน ฿5,000']],v=>max=v?Number(v):Infinity,'boxed'),select('รายการล่าสุด',[['oldest','รายการเก่าสุด'],['price','ราคาน้อยไปมาก']],v=>sort=v||'latest','boxed')));
    const search=h('input',{type:'search','aria-label':'ค้นหาคำสั่งเช่า',placeholder:returns?'ค้นหาสินค้าจาก ชื่อรุ่น, SKU, รหัสออเดอร์':'ค้นหาชุด, ชื่อผู้เช่า, รหัสการเช่า',oninput:e=>{query=e.target.value;draw()}});
    draw();return h('div',{class:'partner-view orders-view'},h('div',{class:'order-mode-tabs'},...[['requests','คำสั่งเช่า','imgSvg9'],['returns','รับชุดคืน','imgSvg10']].map(([key,label,icon])=>h('a',{href:`#closet/${key}`,class:active===key?'active':'','aria-current':active===key?'page':null},h('span',{class:'order-mode-icon'},asset(page,icon)),h('b',{},label)))),title(returns?'รับชุดคืน':'คำสั่งเช่า',returns?'รายการรับชุดคืนของคุณ':'รายการสั่งเช่าของคุณ'),h('section',{class:'partner-order-filter','aria-label':'ค้นหาและกรองคำสั่งเช่า'},tabs,h('div',{class:'partner-filter-row'},h('label',{},asset(page,'imgSvg1'),search),action(asset(page,'imgSvg2'),()=>{selected=groups[0][0];draw()},'partner-filter-icon',{'aria-label':'แสดงรายการทั้งหมด'}),action(asset(page,'imgSvg3'),()=>{const el=filterControls.querySelector('select');el.focus()},'partner-filter-icon',{'aria-label':'เลือกตัวกรอง'})),filterControls),host);
  }
  return h('section',{class:'lender-portal'},header,h('div',{class:'partner-body'},sidebar,h('section',{class:'partner-main','aria-label':'พื้นที่ผู้ปล่อยเช่า'},active==='overview'?overview():active==='listings'?listings():orders(active==='returns'))));
}
