import {h,money,photoUrl,cover} from './dom.js';
import {SLOTS,BODY_DEFAULTS,BODY_LIMITS,IDENTITY,profileStudio,validateStudioBody} from './studio-domain.js';
import {calculateFit} from './mannequin.js';

export function createStudioUI(ctx,catalog,catalogError=''){
 let state=ctx.state,actor=state.settings.currentUserId,profile=profileStudio(state,actor),selected=null,category='',theme='',query='',renderer=null,alive=true;
 const btn=(label,fn,cls='secondary',attrs={})=>h('button',{type:'button',class:cls,...attrs,onclick:()=>ctx.task(fn)},label);
 const muted=text=>h('p',{class:'muted'},text);
 const status=h('div',{class:'studio-status',role:'status','aria-live':'polite'},'กำลังเปิด WebGL…'),host=h('div',{class:'studio-canvas'}),grid=h('div',{class:'studio-grid'}),detail=h('section',{class:'studio-detail','aria-label':'รายละเอียดชิ้นส่วน'}),equipped=h('div',{class:'studio-equipped'}),count=h('span',{class:'studio-count'}),measurements=h('div',{class:'studio-body-fields'}),bodyError=h('p',{class:'form-error',role:'alert'});
 const getItem=id=>state.listings.find(l=>l.id===id),body=()=>profile.bodies[profile.style],seller=id=>state.profiles.find(p=>p.id===id)?.name||'ผู้ให้เช่าเดโม';
 const report=messages=>status.replaceChildren(...(messages.length?messages.map(text=>h('p',{},text)):[h('p',{},'3D พร้อม · ลากเพื่อหมุน 360° · เลื่อนเพื่อซูม')]));
 function draw(){renderer?.update({style:profile.style,body:body(),outfit:profile.outfit,listings:state.listings,bodies:catalog?.bodies});}
 async function saveOutfit(){draw();renderEquipped();renderDetail();if(actor)await ctx.run('studio.outfit.save',{outfit:structuredClone(profile.outfit)});else ctx.toast('เลือกบัญชีเพื่อบันทึกชุดนี้');}
 function wear(item,variant){profile.outfit[item.attachmentSlot]={listingId:item.id,variantId:variant.id,transform:structuredClone(IDENTITY)};selected=item.id;return saveOutfit();}
 function renderEquipped(){equipped.replaceChildren(...Object.entries(SLOTS).map(([slot,label])=>{const ref=profile.outfit[slot],item=getItem(ref?.listingId);return h('div',{class:`equipped-slot ${item?'has-item':''}`},h('span',{},label),item?btn(item.title,()=>{selected=item.id;renderDetail()},'slot-name'):h('small',{},'ยังไม่ได้เลือก'),item?btn('×',()=>{delete profile.outfit[slot];return saveOutfit()},'slot-remove',{'aria-label':`ถอด ${item.title}`}):null)}));}
 function renderBody(){measurements.replaceChildren(...Object.entries(BODY_LIMITS).map(([key,[min,max]])=>h('label',{},h('span',{},({height:'สูง',chest:'อก',waist:'เอว',hip:'สะโพก',shoulder:'ไหล่'})[key]),h('input',{type:'number',min,max,step:1,value:body()[key],'aria-label':`${key} centimeters`,onchange:e=>{const value=Number(e.target.value),next={...body(),[key]:value};if(!validateStudioBody(next)){bodyError.textContent=`กรอกค่าระหว่าง ${min}–${max} ซม.`;return;}bodyError.textContent='';profile.bodies[profile.style]=next;draw();renderDetail();}}))));}
 const stylePicker=h('div',{class:'studio-style-switch',role:'group','aria-label':'เพศหุ่น'},...['female','male'].map(style=>btn(style==='female'?'หญิง / Female':'ชาย / Male',async()=>{profile.style=style;stylePicker.querySelectorAll('button').forEach((el,i)=>el.setAttribute('aria-pressed',String(['female','male'][i]===style)));renderBody();draw();renderDetail();if(actor)await ctx.run('studio.body.save',{style,body:body()});},'',{'aria-pressed':String(profile.style===style)})));
 function renderGrid(){const items=state.listings.filter(l=>l.model&&l.attachmentSlot&&l.status!=='deleted'&&(!category||l.attachmentSlot===category||category==='accessory'&&l.category==='accessory')&&(!theme||l.theme===theme)&&`${l.title} ${l.character} ${l.series}`.toLowerCase().includes(query.toLowerCase()));count.textContent=`${items.length} ชิ้น`;
  grid.replaceChildren(...items.map(item=>{const active=item.status==='active'&&item.sizeVariants.some(v=>v.stock),worn=profile.outfit[item.attachmentSlot]?.listingId===item.id;return h('article',{class:`studio-item ${worn?'is-worn':''}`},btn('',()=>{selected=item.id;renderDetail()},'studio-photo',{'aria-label':`ดู ${item.title}`}),h('div',{class:'studio-item-copy'},h('small',{},`${SLOTS[item.attachmentSlot]} · ${seller(item.sellerId)}`),h('h3',{},item.title),h('div',{class:'studio-item-price'},h('strong',{},`${money(Math.min(...item.sizeVariants.map(v=>v.price)))} / วัน`),h('span',{},item.sizeVariants.map(v=>v.size).join(' / '))),btn(worn?'กำลังใส่ · ปรับแต่ง':'ลองชิ้นนี้ ↗',()=>{selected=item.id;if(worn){renderDetail();return;}return wear(item,item.sizeVariants.find(v=>v.stock)||item.sizeVariants[0])},worn?'dark':'secondary'),!active?h('small',{class:'stock-note'},item.status==='paused'?'พักให้เช่า · ลองได้':'ยังไม่เปิดให้เช่า · ลองได้'):null));}));
  items.forEach((item,i)=>{const img=h('img',{src:photoUrl(cover(item)),alt:`ภาพถ่ายอ้างอิง ${item.title}`,loading:'lazy',onerror:e=>{e.target.replaceWith(h('span',{class:'photo-missing'},'โหลดภาพถ่ายไม่สำเร็จ'));}});grid.children[i].firstChild.append(img,h('span',{class:'photo-label'},'PHOTO REFERENCE'));});
  if(!items.length)grid.append(muted(catalogError||'ไม่พบชิ้นส่วน ลองเปลี่ยนตัวกรอง'));
 }
 function renderDetail(){const item=getItem(selected);if(!item){detail.replaceChildren(h('div',{class:'studio-detail-empty'},h('span',{},'YOUR NEXT CHARACTER'),h('p',{},'เลือกชิ้นส่วนเพื่อดูภาพจริง เลือกไซซ์ แล้วลองผสมข้ามร้าน')));return;}
  const ref=profile.outfit[item.attachmentSlot],worn=ref?.listingId===item.id,variant=item.sizeVariants.find(v=>v.id===(worn?ref.variantId:null))||item.sizeVariants.find(v=>v.stock)||item.sizeVariants[0];
  const sizes=h('div',{class:'studio-sizes'},...item.sizeVariants.map(v=>btn(`${v.size}${v.stock?'':' · หมด'}`,()=>wear(item,v),v.id===variant.id?'dark':'secondary',{'aria-pressed':String(v.id===variant.id)})));
  const adjustments=h('div',{class:'studio-adjustments'});
  if(worn){for(const [key,label,min,max,step,unit]of [['x','ซ้าย / ขวา',-.3,.3,.005,'m'],['y','สูง / ต่ำ',-.3,.3,.005,'m'],['z','หน้า / หลัง',-.3,.3,.005,'m'],['rotation','หมุน',-180,180,1,'°'],['scale','ขนาดภาพ',.5,1.5,.01,'×']]){
   const value=h('output',{},`${ref.transform[key]} ${unit}`),input=h('input',{type:'range',min,max,step,value:ref.transform[key],'aria-label':label,oninput:e=>{ref.transform[key]=Number(e.target.value);value.textContent=`${e.target.value} ${unit}`;draw();},onchange:()=>ctx.task(saveOutfit)});adjustments.append(h('label',{},h('span',{},label,value),input));}
   adjustments.append(btn('คืนตำแหน่งชิ้นนี้',()=>{ref.transform={...IDENTITY};return saveOutfit()},'text-btn'));
  }
  const photo=cover(item),credit=item.photoCredit;detail.replaceChildren(h('div',{class:'studio-detail-heading'},h('div',{},h('small',{},`${SLOTS[item.attachmentSlot]} / ${item.theme||''}`),h('h2',{},item.title)),btn('×',()=>{selected=null;renderDetail()},'icon',{'aria-label':'ปิดรายละเอียด'})),h('div',{class:'studio-detail-content'},h('div',{},h('img',{class:'studio-detail-photo',src:photoUrl(photo),alt:`ภาพถ่ายอ้างอิง ${item.title}`}),credit?h('small',{class:'studio-credit'},'Photo: ',credit.creator||'Source', ' · ',h('a',{href:credit.sourceUrl,target:'_blank',rel:'noopener noreferrer'},credit.license||'Source & license')):muted('ไม่มีข้อมูลเครดิตภาพ')),h('div',{},muted(`ร้าน ${seller(item.sellerId)} · ${item.description}`),h('strong',{class:'studio-detail-price'},`${money(variant.price)} / วัน`),sizes,muted(`ไหล่ ${variant.measurements.shoulder} · อก ${variant.measurements.chest} · เอว ${variant.measurements.waist} · สะโพก ${variant.measurements.hip} · ยาว ${variant.measurements.length} ซม.`),btn(worn?'ถอดชิ้นนี้':'ลองบนหุ่น',()=>{if(worn){delete profile.outfit[item.attachmentSlot];return saveOutfit();}return wear(item,variant)},'secondary'),btn('เช่าชิ้นนี้',()=>ctx.rental(item.id,variant.id),'dark',{disabled:item.status!=='active'||!variant.stock||item.sellerId===actor}),h('a',{class:'text-btn',href:`#product/${item.id}`},'รายละเอียดสินค้า ↗'))),
   worn?h('details',{open:true},h('summary',{},'ปรับชิ้นส่วนบนหุ่น'),adjustments):document.createDocumentFragment(),
   ['top','bottom'].includes(item.attachmentSlot)?h('div',{class:'studio-fit'},h('h3',{},'ประมาณการจากขนาดที่วัด'),...calculateFit(body(),variant.measurements,item.lengthTarget).filter(r=>item.attachmentSlot==='top'?['shoulder','chest','waist'].includes(r.key):['waist','hip','length'].includes(r.key)).map(r=>h('p',{},`${r.label}: ${r.status.replace('_',' ')} — ${r.explanation}`))):document.createDocumentFragment(),
   muted('3D สร้างประมาณจากภาพถ่าย ไม่ใช่สแกนสินค้า สี ทรง และความพอดีอาจต่างจากของจริง'));}
 const toolbar=h('div',{class:'studio-toolbar'},h('label',{class:'studio-search'},h('span',{},'⌕'),h('input',{type:'search',placeholder:'ค้นหาชิ้นส่วน / ตัวละคร','aria-label':'ค้นหาชิ้นส่วน',oninput:e=>{query=e.target.value;renderGrid()}})),h('select',{'aria-label':'ธีม',onchange:e=>{theme=e.target.value;renderGrid()}},h('option',{value:''},'ทุกธีม'),...['academy','fantasy','gothic'].map(t=>h('option',{value:t},t))));
 const categories=h('div',{class:'studio-categories'},...Object.entries({'':'ทุกชิ้น',top:'เสื้อ',bottom:'กางเกง',wig:'วิก',accessory:'เครื่องประดับ'}).map(([key,label])=>btn(label,()=>{category=key;categories.querySelectorAll('button').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.category===key)));renderGrid()},'',{'data-category':key,'aria-pressed':String(key==='')})));
 const root=h('section',{class:'mix-studio'},h('div',{class:'studio-intro'},h('div',{},h('p',{class:'eyebrow'},'CLOSET / THE CHARACTER STUDIO'),h('h1',{},'แต่งตัวละคร',h('em',{},'ในแบบของคุณ'))),muted('เลือกทีละชิ้น · ผสมได้ข้ามร้าน · หมุนดูได้ทุกมุม')),
  h('div',{class:'studio-layout'},h('aside',{class:'studio-left'},h('div',{class:'studio-view'},h('div',{class:'studio-stage-top'},h('span',{},'YOUR MANNEQUIN'),stylePicker),host,h('div',{class:'studio-camera'},btn('หน้า',()=>renderer?.view(0)),btn('ซ้าย',()=>renderer?.view(-Math.PI/2)),btn('หลัง',()=>renderer?.view(Math.PI)),btn('ขวา',()=>renderer?.view(Math.PI/2)),btn('＋',()=>renderer?.zoom(.85),'secondary',{'aria-label':'ขยายหุ่น'}),btn('−',()=>renderer?.zoom(1.15),'secondary',{'aria-label':'ย่อหุ่น'})),status,btn('โหลด 3D ใหม่',()=>renderer?.retry(),'studio-retry text-btn')),h('details',{class:'studio-measurements'},h('summary',{},'สัดส่วนหุ่นของฉัน · ซม.'),measurements,bodyError,h('div',{class:'row'},btn('คืนค่ามาตรฐาน',()=>{profile.bodies[profile.style]=structuredClone(BODY_DEFAULTS[profile.style]);renderBody();draw();renderDetail()}),btn('บันทึกสัดส่วน',async()=>{if(!actor){ctx.accounts();return;}await ctx.run('studio.body.save',{style:profile.style,body:body()});ctx.toast('บันทึกสัดส่วนแล้ว')},'dark')),muted('ปรับรูปทรงโดยประมาณ ขนาดเสื้อผ้าเลือกแยกในแต่ละชิ้น')),h('details',{class:'studio-outfit',open:true},h('summary',{},'ชุดที่กำลังลอง'),equipped)),
   h('div',{class:'studio-right'},h('div',{class:'studio-catalog-heading'},h('h2',{},'เลือกชิ้นที่เป็นคุณ'),count),toolbar,categories,detail,grid,h('p',{class:'studio-footnote'},'ภาพถ่ายอ้างอิงพร้อมเครดิต · ประกาศและราคาเป็นข้อมูลเดโม · ไม่มีการรับเงินจริง'))));
 status.closest('.studio-view').after(muted('พรีวิวจัดทรงตามหุ่นอัตโนมัติ · โมเดลโดยประมาณ ไม่รับประกันความพอดีจริง'));
 renderBody();renderEquipped();renderDetail();renderGrid();
 import('./studio-renderer.js').then(module=>{if(!alive)return;renderer=module.createStudioRenderer(host,report);draw();}).catch(()=>report(['เปิด 3D ไม่สำเร็จ เบราว์เซอร์ต้องรองรับ WebGL และต้องมีไฟล์ Three.js ในเครื่อง']));
 return {element:root,async wearItem(id,variantId){const item=getItem(id);if(!item)throw Error('ไม่พบชิ้นส่วนสำหรับลอง');const variant=item.sizeVariants.find(v=>v.id===variantId)||item.sizeVariants.find(v=>v.stock)||item.sizeVariants[0];await wear(item,variant);detail.scrollIntoView({behavior:'smooth',block:'nearest'});},update(next){state=next;const nextActor=state.settings.currentUserId,actorChanged=actor!==nextActor;actor=nextActor;profile=profileStudio(state,actor);if(actorChanged)selected=null;renderBody();stylePicker.querySelectorAll('button').forEach((el,i)=>el.setAttribute('aria-pressed',String(['female','male'][i]===profile.style)));for(const [slot,ref]of Object.entries(profile.outfit))if(!getItem(ref.listingId)||getItem(ref.listingId).status==='deleted')delete profile.outfit[slot];draw();renderEquipped();renderGrid();renderDetail();},dispose(){alive=false;renderer?.dispose();}};
}
